FROM jupyter/scipy-notebook:python-3.8.13

USER root

ENV SETUP_STATUS="production"
ENV REPO_USER="tna76874"
ENV REPO_NAME="notebooks-school-base"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q && apt-get install -y \
    ghostscript \
    software-properties-common \
    lsb-release \
    gnupg \
    curl \
    wget \
    python3-tk
RUN add-apt-repository universe --yes --update && apt-get install -y \
    shc \
    gcc &\
    rm -rf /var/lib/apt/lists/*

# Setze die Variable für die gcm Version
ARG GCM_VERSION='2.3.2'

# Lade das Debian-Paket herunter
RUN wget https://github.com/git-ecosystem/git-credential-manager/releases/download/v${GCM_VERSION}/gcm-linux_amd64.${GCM_VERSION}.deb && \
    dpkg -i gcm-linux_amd64.${GCM_VERSION}.deb && \
    rm gcm-linux_amd64.${GCM_VERSION}.deb

#INSTALL CLOUDFLARED
# Cloudflare GPG-Key hinzufügen
RUN mkdir -p --mode=0755 /usr/share/keyrings && \
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | gpg --dearmor | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

RUN CODENAME=$(lsb_release -cs) && \
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $CODENAME main" | tee /etc/apt/sources.list.d/cloudflared.list
    
# cloudflared installieren
RUN apt-get update && \
    apt-get install -y --no-install-recommends cloudflared && \
    rm -rf /var/lib/apt/lists/*

COPY ./scripts/docker-entrypoint.sh /
COPY ./scripts/tunnel /usr/local/bin/
COPY ./modules /modules
RUN chmod 775 /usr/local/bin/tunnel

ARG NB_USER=jovyan
ARG NB_UID=1000
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

RUN chmod 775 /docker-entrypoint.sh
COPY ./notebooks/settings.ipynb ${HOME}/settings.ipynb
RUN chown ${NB_USER} ${HOME}/settings.ipynb &&\
    chmod 775 ${HOME}/settings.ipynb &&\
    chown -R ${NB_USER} /modules

USER ${NB_USER}

COPY ./requirements.txt . 

RUN pip install --no-cache-dir -r requirements.txt &&\
    jupyter contrib nbextension install --user &&\
    jupyter nbextension enable varInspector/main && \
    rm -rf requirements.txt &&\
    pip install /modules

RUN rm -rf ${HOME}/work



# set up git env

RUN echo 'export GIT_AUTHOR_NAME="$(whoami)@$(hostname)"' \
    >> /home/${NB_USER}/.bashrc && \
    echo 'export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"' \
    >> /home/${NB_USER}/.bashrc && \
    echo 'export GIT_AUTHOR_EMAIL="$GIT_AUTHOR_NAME"' \
    >> /home/${NB_USER}/.bashrc && \
    echo 'export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_NAME"' \
    >> /home/${NB_USER}/.bashrc  && \
    echo 'git config --global credential.helper cache' \
    >> /home/${NB_USER}/.bashrc

ENTRYPOINT ["/docker-entrypoint.sh"]