name: Docker Image CI

on:
  push:
    branches:
      - master
      - stable
      - dev
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          CURRENT_DATE=$(date +'%Y%m%d')
          CURRENT_DATE_WITH_HOUR=$(date +'%Y%m%d%H')
          IMAGE_NAME="ghcr.io/tna76874/schoolnotebookbase"


          # Set default channel
          CHANNEL=""

          # Determine channel based on branch
          if [ "${{ github.ref }}" == 'refs/heads/master' ]; then
            CHANNEL="latest"
          elif [ "${{ github.ref }}" == 'refs/heads/stable' ]; then
            CHANNEL="stable"
          elif [ "${{ github.ref }}" == 'refs/heads/dev' ]; then
            CHANNEL="dev"
          fi

          # Build and push image for all branches except feature branches
          if [ -n "$CHANNEL" ]; then
            docker build . --file Dockerfile_build --tag "${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE}" --tag "${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE_WITH_HOUR}"
            docker push "${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE}"
            docker push "${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE_WITH_HOUR}"
          fi

          # Build and push image for specific commit
          docker build . --file Dockerfile_build --tag "${IMAGE_NAME}:${COMMIT_HASH}"
          docker push "${IMAGE_NAME}:${COMMIT_HASH}"

          # Build and push image for specific channel
          if [ -n "$CHANNEL" ]; then
            docker build . --file Dockerfile_build --tag "${IMAGE_NAME}:${CHANNEL}"
            docker push "${IMAGE_NAME}:${CHANNEL}"
          fi